export const INCREMENT_ENTHUSIASM="INCREMENT_ENTHUSIASM";
export type INCREMENT_ENTHUSIASM=typeof INCREMENT_ENTHUSIASM;

export const DECREMEMT_ENTHUSIASM="DECREMEMT_ENTHUSIASM";
export type DECREMEMT_ENTHUSIASM=typeof DECREMEMT_ENTHUSIASM;